use_frameworks!

platform :ios, '8.0'

target 'WTabbar_Example' do
  pod 'WTabbar', :path => '../'
  pod 'lottie-ios',               '2.5.3'
  target 'WTabbar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
